/**
 * Code generation shared by `pnpm --filter @graphgoblin/api-client generate` and the drift tests,
 * so both produce byte-identical output. Node-only; never imported from `src/` production code.
 */
import { readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { emitOpenApi } from '@graphgoblin/api';
import openapiTS, { astToString } from 'openapi-typescript';
import ts from 'typescript';

const packageRoot = join(dirname(fileURLToPath(import.meta.url)), '..');

export const OPENAPI_PATH = join(packageRoot, 'openapi.json');
export const SCHEMA_PATH = join(packageRoot, 'src', 'generated', 'schema.ts');
export const GENERATE_HINT = 'run `pnpm --filter @graphgoblin/api-client generate` and commit';

const HEADER = `/**
 * Generated by openapi-typescript from packages/api-client/openapi.json. Do not edit by hand:
 * ${GENERATE_HINT} the result.
 */

/**
 * Any JSON value. Declared here because TypeScript rejects the recursive \`JsonValue\` component
 * when it is written inline as an interface member; both JSON components point at this alias.
 */
export type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };

`;

const RECURSIVE_JSON_COMPONENTS = new Set([
  '#/components/schemas/JsonValue',
  '#/components/schemas/JsonValueInput',
]);

/** The API's OpenAPI document as the API emits it (pretty-printed JSON with a trailing newline). */
export async function liveOpenApiDocument(): Promise<string> {
  return `${await emitOpenApi()}\n`;
}

/** TypeScript declarations for an OpenAPI document. */
export async function typesFor(document: string): Promise<string> {
  const ast = await openapiTS(JSON.parse(document) as Parameters<typeof openapiTS>[0], {
    alphabetize: false,
    // A `default` makes a property optional on input; do not mark it required.
    defaultNonNullable: false,
    // Optional properties also accept `undefined`, matching what Zod infers for the contracts, so
    // contract-typed values pass under `exactOptionalPropertyTypes`. JSON drops undefined anyway.
    transformProperty: (property) =>
      property.questionToken && property.type
        ? ts.factory.updatePropertySignature(
            property,
            property.modifiers,
            property.name,
            property.questionToken,
            ts.factory.createUnionTypeNode([
              property.type,
              ts.factory.createKeywordTypeNode(ts.SyntaxKind.UndefinedKeyword),
            ]),
          )
        : undefined,
    transform: (_schema, { path }) =>
      path && RECURSIVE_JSON_COMPONENTS.has(path)
        ? ts.factory.createTypeReferenceNode('JsonValue')
        : undefined,
  });
  return HEADER + astToString(ast);
}

export async function readCommitted(): Promise<{ document: string; types: string }> {
  const [document, types] = await Promise.all([
    readFile(OPENAPI_PATH, 'utf8'),
    readFile(SCHEMA_PATH, 'utf8'),
  ]);
  return { document, types };
}
